import com.rhc.stock.Stock
import com.rhc.stock.StockDay
import com.rhc.stock.StockQuote

rule 'helloWorld'
	when
		$stock : Stock(name == "GOOG")
	then
		System.out.println("GOOGLE GOOGLE GOOGLE !!!!");
end

rule 'bidToBuyStock'
	when
		$quote : StockQuote()
		
		$day : StockDay
		(
			stock.name == $quote.stock.name, 
			dayOpen > $quote.price + $quote.volatility
		)
		
	then
		insert ( new String ( "buy") );
end


rule 'askToSellStock'
	when
		$quote : StockQuote()
		$day : StockDay
		(
			stock.getName() == $quote.getStock().getName(), 
			dayOpen < $quote.getPrice() - $quote.volatility
		)
	then
		insert ( new String ( "sell") );
end

query "Get actions"

	$action : String()
	
end
